dist: trusty
language: java
jdk:
  - openjdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report
  - mvn package

cache:
  directories:
    - $HOME/.m2